# Generated by Django 5.2.9 on 2026-01-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EdTube', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
