# Generated by Django 5.2.9 on 2026-01-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_pfp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='t_id',
            new_name='teacher_id',
        ),
    ]
