# Generated by Django 5.2.9 on 2026-01-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_banner/'),
        ),
    ]
