# Generated by Django 5.2.9 on 2026-02-01 10:04

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_banner_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='banner_img',
        ),
        migrations.AddField(
            model_name='teacher',
            name='banner',
            field=models.ImageField(blank=True, help_text='Profile picture (max 10MB - Cloudinary Free limit)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='teacher_banner/', validators=[cloudinary_storage.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pfp',
            field=models.ImageField(blank=True, help_text='Profile picture (max 10MB - Cloudinary Free limit)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='teacher_profiles/', validators=[cloudinary_storage.validators.validate_image]),
        ),
    ]
