# Generated by Django 5.2.9 on 2026-02-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_teacher_banner_img_teacher_banner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='banner',
            new_name='banner_img',
        ),
    ]
