# Generated by Django 5.2.9 on 2026-02-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_rename_banner_teacher_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='center_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree_pursued',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
