# Generated by Django 5.2.9 on 2026-02-19 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_teacher_center_address_teacher_degree_pursued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
    ]
