# Generated by Django 5.2.9 on 2026-01-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='otp',
            field=models.CharField(max_length=4),
        ),
    ]
