# Generated by Django 5.2.9 on 2026-02-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailverification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='otp_purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], default='registration', max_length=20),
        ),
    ]
