# Generated by Django 5.2.9 on 2026-02-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverification_otp_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='otp_purpose',
            new_name='purpose',
        ),
    ]
