# Generated by Django 5.2.9 on 2026-02-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_otp_purpose_emailverification_purpose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='purpose',
            new_name='otp_purpose',
        ),
    ]
