# Generated by Django 5.2.9 on 2026-01-16 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('no_of_quiz_given', models.PositiveIntegerField(default=0)),
                ('no_of_points_earned', models.PositiveIntegerField(default=0)),
                ('rank_in_leaderboard', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
