# Generated by Django 5.2.9 on 2026-02-01 10:04

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pfp',
            field=models.ImageField(blank=True, help_text='Profile picture (max 10MB - Cloudinary Free limit)', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='student_profiles/', validators=[cloudinary_storage.validators.validate_image]),
        ),
    ]
