# Generated by Django 5.2.9 on 2026-02-19 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_coins_cointransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bio',
        ),
    ]
