# Generated by Django 5.2.9 on 2026-02-19 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_bio'),
        ('video', '0010_video_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.video'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('student', 'video')},
        ),
    ]
