# Generated by Django 5.2.9 on 2026-02-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_quizattempt_video_alter_quizattempt_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('student', 'quiz_id')},
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='video',
        ),
    ]
