# Generated by Django 5.2.9 on 2026-02-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_quizattempt_percentage_quizattempt_total_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuizCoinsRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quiz_coins_redemptions', to='student.student')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
