# Generated by Django 5.2.9 on 2026-01-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_teacher_pfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('language', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('notes', models.FileField(blank=True, null=True, upload_to='video_notes/')),
                ('quiz', models.FileField(blank=True, null=True, upload_to='video_quizzes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='teacher.teacher')),
            ],
        ),
    ]
