# Generated by Django 5.2.9 on 2026-01-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, default='0:00', max_length=10),
        ),
    ]
