# Generated by Django 5.2.9 on 2026-01-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_comment_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
