# Generated by Django 5.2.9 on 2026-01-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
