# Generated by Django 5.2.9 on 2026-02-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_video_notes_alter_video_quiz_and_more'),
        ('video', '0006_video_views_count'),
    ]

    operations = [
    ]
