# Generated by Django 5.2.9 on 2026-02-17 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_quiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('watch_duration', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_history', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.video')),
            ],
            options={
                'ordering': ['-watched_at'],
                'indexes': [models.Index(fields=['user', '-watched_at'], name='video_video_user_id_42b1fe_idx'), models.Index(fields=['user', 'video'], name='video_video_user_id_b6d535_idx')],
                'unique_together': {('user', 'video', 'watched_at')},
            },
        ),
    ]
