# Generated by Django 5.2.9 on 2026-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_videohistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='quiz_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
